Added ping call to script

diff --git a/startSwarm b/startSwarm
--- a/startSwarm
+++ b/startSwarm
@@ -29,7 +29,24 @@ BOOTSTRAP_IP=${IP_LIST[0]}
 echo "Setting up Queen node at IP $BOOTSTRAP_IP:"
 ssh -i "$SSH_KEY" -f "$SSH_USER@$BOOTSTRAP_IP" 'cd p4-final-r-2 && make && nohup java -cp lib/*:. anthill.Drone --initialize &' # replace '&' with ' > /dev/null 2>&1 &' to throw away output
 
-wait 
+PING_BS=false
+PING_COUNT=0
+while [[ "$PING_BS" == false && "$PING_COUNT" < 3]]; do
+    echo "Checking if Queen node is ready..."
+    if ssh -i "$SSH_KEY" "$SSH_USER@$BOOTSTRAP_IP" 'java -cp p4-final-r-2/lib/*: p4-final-r-2/Drone ping'; then
+        QUEEN_READY=true
+        echo "Queen node is ready."
+    else
+        sleep 5
+        ((PING_COUNT++))
+    fi
+done
+
+if [$PING_COUNT >= 3]; then
+    echo "Could not ping Queen node."
+    exit 1
+fi
+
 
 for ip_address in "${IP_LIST[@]:1}"; do
     (
@@ -40,7 +57,7 @@ for ip_address in "${IP_LIST[@]:1}"; do
 done 
 
 wait
-clear
+
 echo "All Drones have been accepted by the Queen."
 
 cat << 'EOF'
